<?php include 'header.php' ?>
<?php include 'sidebar.php' ?>
<?php  $sentencia = $connect->prepare("SELECT * FROM `wp_propiedades`") or die('query failed');
        $sentencia->execute();
        $consultasXpagina = 40;
        $consultasTotales = $sentencia->rowCount();
        $paginas = $consultasTotales/$consultasXpagina;
        $paginas = ceil($paginas);
        if(!isset($_POST['seleccionarOperacion'])){$_POST['seleccionarOperacion'] = '';};
        if(!isset($_POST['seleccionarTipo'])){$_POST['seleccionarTipo'] = '';};
        if(!isset($_POST['seleccionarCiudad'])){$_POST['seleccionarCiudad'] = '';};
        if(!isset($_POST['buscarPrecioDesde'])){$_POST['buscarPrecioDesde'] = '';};
        if(!isset($_POST['buscarPrecioHasta'])){$_POST['buscarPrecioHasta'] = '';};
        if(!isset($_POST['buscarHabitacionesDesde'])){$_POST['buscarHabitacionesDesde'] = '';};
        if(!isset($_POST['buscarHabitacionesHasta'])){$_POST['buscarHabitacionesHasta'] = '';};
        if(!isset($_POST['buscarDomicilio'])){$_POST['buscarDomicilio'] = '';};
        if(!isset($_POST['buscarReferencia'])){$_POST['buscarReferencia'] = '';};
        if(!isset($_POST['buscarPileta'])){$_POST['buscarPileta'] = '';};
        if(!isset($_POST['buscarLlaves'])){$_POST['buscarLlaves'] = '';};
        if(!isset($_POST['buscarOcupada'])){$_POST['buscarOcupada'] = '';};
        if(!isset($_POST['buscarPlantaBaja'])){$_POST['buscarPlantaBaja'] = '';};
        if(!isset($_POST['buscarEstado'])){$_POST['buscarEstado'] = '';};
        if(!$_GET || $_GET["pagina"]<1){header('Location:propiedades.php?pagina=1&op='.$_POST['seleccionarOperacion'].'&tipo='.$_POST['seleccionarTipo'].'&ciudad='.$_POST['seleccionarCiudad'].'&zona='.$_POST['seleccionarZona'].'&preciodesde='.$_POST['buscarPrecioDesde'].'&preciohasta='.$_POST['buscarPrecioHasta'].'&habitacionesdesde='.$_POST['buscarHabitacionesDesde'].'&habitacioneshasta='.$_POST['buscarHabitacionesHasta'].'&domicilio='.$_POST['buscarDomicilio'].'&ref='.$_POST['buscarReferencia'].'&pileta='.$_POST['buscarPileta'].'&llaves='.$_POST['buscarLlaves'].'&ocupada='.$_POST['buscarOcupada'].'&plantabaja='.$_POST['buscarPlantaBaja'].'&estado='.$_POST['buscarEstado']);}elseif($_GET['pagina']>$paginas){header('Location:propiedades.php?pagina=1&op='.$_POST['seleccionarOperacion'].'&tipo='.$_POST['seleccionarTipo'].'&ciudad='.$_POST['seleccionarCiudad'].'&zona='.$_POST['seleccionarZona'].'&preciodesde='.$_POST['buscarPrecioDesde'].'&preciohasta='.$_POST['buscarPrecioHasta'].'&habitacionesdesde='.$_POST['buscarHabitacionesDesde'].'&habitacioneshasta='.$_POST['buscarHabitacionesHasta'].'&domicilio='.$_POST['buscarDomicilio'].'&ref='.$_POST['buscarReferencia'].'&pileta='.$_POST['buscarPileta'].'&llaves='.$_POST['buscarLlaves'].'&ocupada='.$_POST['buscarOcupada'].'&plantabaja='.$_POST['buscarPlantaBaja']);}
?>
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <!--/* Main */-->
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <main class="main" id="main">
            <div class="main__container">
                <div class="main__container__top">
                    <div class="main__title"><i class="fa-solid fa-building main__h1--emoji"></i><h1 class="main__h1">Propiedades</h1></div>
                    <div class="main__buttons">
                        <button class="main__buttons__button">Agregar Propiedad</button>
                        <button class="main__buttons__button">Descargar Ficha</button>
                    </div>
                </div>
                <div class="main__decoration"></div>
                <div class="main__busqueda-propiedad">
                    <form class="form__busqueda-propiedad form" name="form" method="POST" action="propiedades.php">
                        <div class="form__bloque">
                            <div class="form__bloque__content content"> 
                                <label  class="form__label content__label" for="">Operación</label>
                                <select class="form__select content__select" name="seleccionarOperacion" id="">                      
                                <?php if($_GET['op'] != ''){
                                    $id= $_GET['op'];
                                    $sentencia = $connect->prepare("SELECT * FROM `wp_propiedad_operacion` WHERE id= $id") or die('query failed');
                                    $sentencia->execute();
                                    $list_propiedades = $sentencia->fetchAll();                         
                                    foreach($list_propiedades as $propiedad){
                                    $propiedadNombre = $propiedad['nombre'];?>
                                    <option value="<?php echo $_GET['op'];?>"><?php echo $propiedadNombre;?></option>
                                <?php };};?>
                                    <option value></option>
                                    <?php                          
                                        $sentencia = $connect->prepare("SELECT * FROM `wp_propiedad_operacion` WHERE habilitado=1") or die('query failed');
                                        $sentencia->execute();
                                        $list_propiedades = $sentencia->fetchAll();                         
                                        foreach($list_propiedades as $propiedad){
                                        $idPropiedad = $propiedad['id'];
                                        $propiedadNombre = $propiedad['nombre'];
                                        if($_GET['op']!=$idPropiedad){?>
                                    <option value="<?php echo $idPropiedad?>"><?php echo $propiedadNombre?></option>
                                <?php };};?>
                                </select>
                            </div>
                            <div class="form__bloque__content content">
                                <label  class="form__label content__label" for="">Tipo</label>
                                <select class="form__select content__select" name="seleccionarTipo" id="">    
                                <?php if($_GET['tipo'] != ''){
                                    $id= $_GET['tipo'];
                                    $sentencia = $connect->prepare("SELECT * FROM `wp_propiedad_tipo` WHERE id= $id") or die('query failed');
                                    $sentencia->execute();
                                    $list_propiedades = $sentencia->fetchAll();                         
                                    foreach($list_propiedades as $propiedad){
                                    $propiedadNombre = $propiedad['nombre'];?>
                                    <option value="<?php echo $_GET['tipo'];?>"><?php echo $propiedadNombre;?></option>
                                <?php };};?>
                                    <option value></option>
                                    <?php                          
                                        $sentencia = $connect->prepare("SELECT * FROM `wp_propiedad_tipo` WHERE habilitado=1") or die('query failed');
                                        $sentencia->execute();
                                        $list_propiedadesOperacion = $sentencia->fetchAll();                         
                                        foreach($list_propiedadesOperacion as $propiedad){
                                        $idPropiedad = $propiedad['id'];
                                        $propiedadNombre = $propiedad['nombre'];
                                        if($_GET['tipo']!=$idPropiedad){?>
                                    <option value="<?php echo $idPropiedad?>"><?php echo $propiedadNombre?></option>
                                <?php };};?>
                                </select>
                            </div>
                            <div class="form__bloque__content content">
                                <label  class="form__label content__label" for="">Ciudad</label>
                                <select class="form__select content__select" name="seleccionarCiudad" id="">
                                <?php if($_GET['ciudad'] != ''){
                                        $id= $_GET['ciudad'];
                                        $sentencia = $connect->prepare("SELECT * FROM `wp_ciudades` WHERE id= $id") or die('query failed');
                                        $sentencia->execute();
                                        $list_propiedades = $sentencia->fetchAll();                         
                                        foreach($list_propiedades as $propiedad){
                                        $propiedadNombre = $propiedad['nombre'];?>
                                        <option value="<?php echo $_GET['ciudad'];?>"><?php echo $propiedadNombre;?></option>
                                    <?php };};?>
                                        <option value></option>
                                        <?php                          
                                            $sentencia = $connect->prepare("SELECT * FROM `wp_ciudades` WHERE habilitado=1") or die('query failed');
                                            $sentencia->execute();
                                            $list_propiedadesOperacion = $sentencia->fetchAll();                         
                                            foreach($list_propiedadesOperacion as $propiedad){
                                            $idPropiedad = $propiedad['id'];
                                            $propiedadNombre = $propiedad['nombre'];
                                            if($_GET['ciudad']!=$idPropiedad){?>
                                        <option value="<?php echo $idPropiedad?>"><?php echo $propiedadNombre?></option>
                                    <?php };};?>
                                </select>
                            </div>
                            <div class="form__bloque__content content">
                                <label  class="form__label content__label" for="">Zona</label>
                                <select class="form__select content__select" name="seleccionarZona" id="">
                                <?php if($_GET['zona'] != ''){
                                        $id= $_GET['zona'];
                                        $sentencia = $connect->prepare("SELECT * FROM `wp_zonas` WHERE id= $id") or die('query failed');
                                        $sentencia->execute();
                                        $list_propiedades = $sentencia->fetchAll();                         
                                        foreach($list_propiedades as $propiedad){
                                        $propiedadNombre = $propiedad['nombre'];?>
                                        <option value="<?php echo $_GET['zona'];?>"><?php echo $propiedadNombre;?></option>
                                    <?php };};?>
                                        <option value></option>
                                        <?php                          
                                            $sentencia = $connect->prepare("SELECT * FROM `wp_zonas` WHERE habilitada=1") or die('query failed');
                                            $sentencia->execute();
                                            $list_propiedadesOperacion = $sentencia->fetchAll();                         
                                            foreach($list_propiedadesOperacion as $propiedad){
                                            $idPropiedad = $propiedad['id'];
                                            $propiedadNombre = $propiedad['nombre'];
                                            if($_GET['zona']!=$idPropiedad){?>
                                        <option value="<?php echo $idPropiedad?>"><?php echo $propiedadNombre?></option>
                                    <?php };};?>
                                </select>
                            </div>
                        </div>
                        <div class="form__bloque form__bloque--2">
                            <div class="form__bloque__precio precio">
                                <h2 class="precio__h2">Precio</h2>
                                <div class="precio__container">
                                    <div class="form__bloque__content precio__container__content">
                                        <label  class="form__label precio__container__content__label" for="">Desde</label>
                                    <input class="form__text precio__container__content__text" name="buscarPrecioDesde" value="<?php echo $_GET['preciodesde']?>" type="text">
                                    </div>
                                    <div class="form__bloque__content precio__container__content">
                                        <label  class="form__label precio__container__content__label" for="">Hasta</label>
                                        <input class="form__text precio__container__content__text" name="buscarPrecioHasta" value="<?php echo $_GET['preciohasta']?>" type="text">
                                    </div>
                                </div>                            
                            </div>
                            <div class="form__bloque__habitaciones habitaciones">
                                <h2 class="habitaciones__h2">Habitaciones</h2>
                                <div class="habitaciones__container">
                                    <div class="form__bloque__content habitaciones__container__content">
                                        <label  class="form__label habitaciones__container__content__label" for="">Desde</label>
                                        <input class="form__text habitaciones__container__content__text" name="buscarHabitacionesDesde" value="<?php echo $_GET['habitacionesdesde']?>"  type="text">
                                    </div>
                                    <div class="form__bloque__content habitaciones__container__content">
                                        <label  class="form__label habitaciones__container__content__label" for="">Hasta</label>
                                        <input class="form__text habitaciones__container__content__text" name="buscarHabitacionesHasta" value="<?php echo $_GET['habitacioneshasta']?>" type="text">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form__bloque">
                            <div class="form__bloque__content content">
                                <label  class="form__label content__label" for="">Domicilio</label>
                                <input class="form__text habitaciones__container__content__text" name="buscarDomicilio" value="<?php echo $_GET['domicilio']?>" type="text">
                            </div>
                            <div class="form__bloque__content content">
                                <label  class="form__label content__label" for="">Referencia</label>
                                <input class="form__text habitaciones__container__content__text" name="buscarReferencia" value="<?php echo $_GET['ref']?>" type="text">
                            </div>
                            <div class="form__bloque__content content">
                                <label class="form__label content__label" for="">Pileta</label>
                            <input class="form__checkbox content__checkbox" type="checkbox" name="buscarPileta" value="1" <?php if($_GET['pileta']==1){ echo 'checked="check"';}?>>
                            </div>
                            <div class="form__bloque__content content">
                                <label class="form__label content__label" for="">Llaves</label>
                                <input class="form__checkbox content__checkbox" type="checkbox" name="buscarLlaves" value="si" <?php if($_GET['llaves']=='si'){ echo 'checked="check"';}?>>
                            </div>
                            <div class="form__bloque__content content">
                                <label class="form__label content__label" for="">Ocupada</label>
                                <input class="form__checkbox content__checkbox" type="checkbox" name="buscarOcupada" value="1" <?php if($_GET['ocupada']==1){ echo 'checked="check"';}?>>
                            </div>
                            <div class="form__bloque__content content">
                                <label class="form__label content__label" for="">Planta baja</label>
                                <input class="form__checkbox content__checkbox" type="checkbox" name="buscarPlantaBaja" value="1" <?php if($_GET['plantabaja']==1){ echo 'checked="check"';}?>>
                            </div>
                        </div>
                        <div class="form__bloque">
                            <div class="form__bloque__content content">
                                <label  class="form__label content__label" for="">Estado de publicación</label>
                                <select class="form__select" name="buscarEstado">
                                <?php if($_GET['estado'] != ''){
                                        $id= $_GET['estado'];
                                        $sentencia = $connect->prepare("SELECT * FROM `wp_estados_publicacion` WHERE id= $id") or die('query failed');
                                        $sentencia->execute();
                                        $list_propiedades = $sentencia->fetchAll();                         
                                        foreach($list_propiedades as $propiedad){
                                        $propiedadNombre = $propiedad['nombre'];?>
                                        <option value="<?php echo $_GET['estado'];?>"><?php echo $propiedadNombre;?></option>
                                    <?php };};?>
                                        <option value></option>
                                        <?php                          
                                            $sentencia = $connect->prepare("SELECT * FROM `wp_estados_publicacion` WHERE habilitado=1") or die('query failed');
                                            $sentencia->execute();
                                            $list_propiedadesOperacion = $sentencia->fetchAll();                         
                                            foreach($list_propiedadesOperacion as $propiedad){
                                            $idPropiedad = $propiedad['id'];
                                            $propiedadNombre = $propiedad['nombre'];
                                            if($_GET['estado']!=$idPropiedad){?>
                                        <option value="<?php echo $idPropiedad?>"><?php echo $propiedadNombre?></option>
                                    <?php };};?>
                                </select>
                            </div>
                        </div>
                        <div class="form__bloque form__bloque--5">
                            <input type="submit" class="form__button form__bloque__button" value="Buscar">
                            <input type="button" class="form__button form__bloque__button" value="Guardar filtros">
                            <input class="form__text form__bloque__text" type="text" placeholder="Nombre del filtro">
                            <select class="form__select form__bloque__select" name="" id="">
                                <option value="1">Filtros guardados</option>
                            </select>
                        </div>
                    </form>
                </div>
                <div class="main__decoration"></div>
                <div class="propiedades">
                    <ul class="propiedades__ul">
                    <?php
			        $whereOp="op.id = ".$_GET['op'];         
                    $whereTipo="tipo.id = ".$_GET['tipo'];
                    $whereCiudad="ciudad.id = ".$_GET['ciudad'];
                    $whereZona="zona.id = ".$_GET['zona'];
                    $wherePrecio="prop.precio_propietario BETWEEN ".$_GET['preciodesde']."AND".$_GET['preciohasta'];
                    $whereHabitaciones="prop.cant_habitaciones BETWEEN ".$_GET['habitacionesdesde']." AND ".$_GET['habitacioneshasta'];
                    $whereDomicilio="prop.calle LIKE '%".$_GET['domicilio']."%'";
                    $whereRef="prop.referencia_interna LIKE '%".$_GET['ref']."%'";
                    $wherePileta="prop.pileta_propia = ".$_GET['pileta']." OR prop.pileta_compartida = ".$_GET['pileta'];
                    $whereLlaves="prop.llavero = '".$_GET['llaves']."'";
                    $whereOcupada="prop.ocupada = ".$_GET['ocupada'];
                    $wherePlantaBaja="prop.planta_baja = ".$_GET['plantabaja'];
                    $whereEstado="prop.visible_web = ".$_GET['estado'];
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = '';}else{ 
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereOp." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereTipo." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereCiudad." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereZona." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$wherePrecio." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereHabitaciones." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] != '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereDomicilio." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] != '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereRef." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] != '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$wherePileta." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereLlaves." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereOcupada." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$wherePlantaBaja." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] == '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] == '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] == '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] == '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] == '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] == '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] == '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] == '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] == '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] == '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] == '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." ";};
                    
                    }
                        $inicioConsultasXpagina = ($_GET['pagina'] - 1)*$consultasXpagina;
                        $sentencia = $connect->prepare("SELECT prop.id, prop.foto_portada, prop.tipo_propiedad_id, prop.operacion_id, prop.zona_id, prop.metros_utiles, prop.cant_habitaciones, prop.nro_banios, prop.precio_propietario, prop.visible_web, prop.ciudad_id, prop.calle, prop.referencia_interna, prop.llavero, prop.ocupada, prop.planta_baja,
                        tipo.id, tipo.nombre,
                        op.id, op.nombre,
                        zona.id, zona.nombre,
                        ciudad.id,
                        prop.id as prop_id, prop.foto_portada as prop_foto_portada, prop.tipo_propiedad_id as prop_tipo_propiedad_id, prop.operacion_id as prop_operacion_id, prop.zona_id as prop_zona_id, prop.metros_utiles as prop_metros_utiles, prop.cant_habitaciones as prop_cant_habitaciones, prop.nro_banios as prop_nro_banios, prop.precio_propietario as prop_precio_propietario, prop.visible_web as prop_visible_web, prop.ciudad_id as prop_ciudad_id, prop.calle as prop_calle, prop.referencia_interna as prop_referencia_interna, prop.llavero as prop_llavero, prop.ocupada as prop_ocupada, prop.planta_baja as prop_planta_baja,
                        tipo.id as tipo_id, tipo.nombre as tipo_nombre,
                        op.id as op_id, op.nombre as op_nombre,
                        zona.id as zona_id, zona.nombre as zona_nombre,
                        ciudad.id as ciudad_id  
                        FROM wp_propiedades prop 
                        LEFT JOIN wp_propiedad_tipo tipo ON  prop.tipo_propiedad_id =tipo.id
                        LEFT JOIN wp_propiedad_operacion op ON  prop.operacion_id=op.id
                        LEFT JOIN wp_zonas zona ON  prop.zona_id=zona.id
                        LEFT JOIN wp_ciudades ciudad ON  prop.ciudad_id=ciudad.id
                        $filtro") or die('query failed');
                        $sentencia->execute();
                        $list_propiedades = $sentencia->fetchAll(PDO::FETCH_ASSOC);
                        $consultasTotales = $sentencia->rowCount();
                        $paginas = $consultasTotales/$consultasXpagina;
                        $paginas = ceil($paginas);?>


                    <?php
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = '';}else{ 
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereOp." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereTipo." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereCiudad." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereZona." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$wherePrecio." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereHabitaciones." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] != '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereDomicilio." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] != '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereRef." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] != '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$wherePileta." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereLlaves." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereOcupada." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$wherePlantaBaja." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] == '' AND $_GET['ref'] == '' AND $_GET['pileta'] == '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] == '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] == '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] == '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereCiudad." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] == '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereTipo." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] == '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] == '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] == '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] == '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$whereEstado." ";};
                    if($_GET['op'] == '' AND $_GET['tipo'] != '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereTipo." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] == '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] == '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] == '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] == '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] == '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] == '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] == '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] == '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereOcupada." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] == '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$wherePlantaBaja." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] == '' AND $_GET['estado'] != ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$whereEstado." ";};
                    if($_GET['op'] != '' AND $_GET['tipo'] == '' AND $_GET['ciudad'] != '' AND $_GET['zona'] != '' AND $_GET['preciodesde'] != '' AND $_GET['habitacionesdesde'] != '' AND $_GET['domicilio'] != '' AND $_GET['ref'] != '' AND $_GET['pileta'] != '' AND $_GET['llaves'] != '' AND $_GET['ocupada'] != '' AND $_GET['plantabaja'] != '' AND $_GET['estado'] == ''){$filtro = "WHERE ".$whereOp." AND ".$whereCiudad." AND ".$whereZona." AND ".$wherePrecio." AND ".$whereHabitaciones." AND ".$whereDomicilio." AND ".$whereRef." AND ".$wherePileta." AND ".$whereLlaves." AND ".$whereOcupada." AND ".$wherePlantaBaja." ";};
                    
                    }
                        $inicioConsultasXpagina = ($_GET['pagina'] - 1)*$consultasXpagina;
                        $sentencia = $connect->prepare("SELECT prop.id, prop.foto_portada, prop.tipo_propiedad_id, prop.operacion_id, prop.zona_id, prop.metros_utiles, prop.cant_habitaciones, prop.nro_banios, prop.precio_propietario, prop.visible_web, prop.ciudad_id, prop.calle, prop.referencia_interna, prop.llavero, prop.ocupada, prop.planta_baja,
                        tipo.id, tipo.nombre,
                        op.id, op.nombre,
                        zona.id, zona.nombre,
                        ciudad.id,
                        prop.id as prop_id, prop.foto_portada as prop_foto_portada, prop.tipo_propiedad_id as prop_tipo_propiedad_id, prop.operacion_id as prop_operacion_id, prop.zona_id as prop_zona_id, prop.metros_utiles as prop_metros_utiles, prop.cant_habitaciones as prop_cant_habitaciones, prop.nro_banios as prop_nro_banios, prop.precio_propietario as prop_precio_propietario, prop.visible_web as prop_visible_web, prop.ciudad_id as prop_ciudad_id, prop.calle as prop_calle, prop.referencia_interna as prop_referencia_interna, prop.llavero as prop_llavero, prop.ocupada as prop_ocupada, prop.planta_baja as prop_planta_baja,
                        tipo.id as tipo_id, tipo.nombre as tipo_nombre,
                        op.id as op_id, op.nombre as op_nombre,
                        zona.id as zona_id, zona.nombre as zona_nombre,
                        ciudad.id as ciudad_id  
                        FROM wp_propiedades prop 
                        LEFT JOIN wp_propiedad_tipo tipo ON  prop.tipo_propiedad_id =tipo.id
                        LEFT JOIN wp_propiedad_operacion op ON  prop.operacion_id=op.id
                        LEFT JOIN wp_zonas zona ON  prop.zona_id=zona.id
                        LEFT JOIN wp_ciudades ciudad ON  prop.ciudad_id=ciudad.id
                        $filtro ORDER BY prop_id DESC LIMIT $inicioConsultasXpagina,$consultasXpagina") or die('query failed');
                        $sentencia->execute();
                        $list_propiedades = $sentencia->fetchAll(PDO::FETCH_ASSOC);
                        foreach($list_propiedades as $propiedad){
                            $imgPropiedad = strval($propiedad['prop_foto_portada']);
                            $imgPropiedad = str_replace('"', '', $imgPropiedad);;
                            $imgPropiedad = str_replace("[", "", $imgPropiedad);
                            $imgPropiedad = str_replace("]", "", $imgPropiedad);
                            $metrosPropiedad = floatval($propiedad['prop_metros_utiles']);
                            $habitacionesPropiedad = $propiedad['prop_cant_habitaciones'];
                            $baniosPropiedad = $propiedad['prop_nro_banios'];
                            $precioPropiedad = intval($propiedad['prop_precio_propietario']);
                            $enWeb = intval($propiedad['prop_visible_web']);
                            $tipoPropiedad = $propiedad['tipo_nombre'];
                            $operacionPropiedad = $propiedad['op_nombre'];
                            $zonaPropiedad = $propiedad['zona_nombre'];                                                                   
                        ?>                           
                        <li class="propiedades__li">
                            <img class="propiedades__img" src="<?php echo 'https://projectandbrokers.com/wp-content/uploads/thumbnails/mediano__'.$imgPropiedad?>" alt="">
                            <div class="propiedades__nombre-detalles-precio">
                                <span class="propiedades__nombre"><?php echo $tipoPropiedad.' en '.$operacionPropiedad.' '.$zonaPropiedad;?></span>
                                <span class="propiedades__detalles"><?php echo $metrosPropiedad.'m2 | '.$habitacionesPropiedad,' hab | '.$baniosPropiedad.' Baños'?></span>
                                <span class="propiedades__precio"><?php echo 'U$S '.number_format($precioPropiedad,0,",", ".").' | U$S '.intval($precioPropiedad/$metrosPropiedad).'/m2'?></span>
                            </div>
                            <span class="propiedades__estado"><?php if ($enWeb==1){echo 'En web';}else{echo 'No publicada';}?></span>
                            <div class="propiedades__edit-hide">
                                <a href=""><i class="propiedades__accion fa-solid fa-pencil"></i></a>
                                <a href=""><i class="propiedades__accion fa-solid fa-eye-slash"></i></a>
                            </div>
                        </li>
                    <?php };?>
                    </ul>
                </div>
                <div class="pagination">
                    <ul>
                        <a class="<?php if ($_GET['pagina']<=1){echo 'is-disabled';}?>" href="propiedades.php?pagina=<?php echo $_GET["pagina"]-1?>&op=<?php echo $_GET['op']?>&tipo=<?php echo $_GET['tipo']?>&ciudad=<?php echo $_GET['ciudad']?>&zona=<?php echo $_GET['zona']?>&preciodesde=<?php echo $_GET['preciodesde']?>&preciohasta=<?php echo $_GET['preciohasta']?>&habitacionesdesde=<?php echo $_GET['habitacionesdesde']?>&habitacioneshasta=<?php echo $_GET['habitacioneshasta']?>&domicilio=<?php echo $_GET['domicilio']?>&ref=<?php echo $_GET['ref']?>&pileta=<?php echo $_GET['pileta']?>&llaves=<?php echo $_GET['llaves']?>&ocupada=<?php echo $_GET['ocupada']?>&plantabaja=<?php echo $_GET['plantabaja']?>&estado=<?php echo $_GET['estado']?>"><li><</li></a>
				        <?php for($i=0;$i<$paginas;$i++):?>
                        <a class="<?php if ($_GET['pagina']==$i+1){echo 'is-active';}?>" href="propiedades.php?pagina=<?php echo $i+1?>&op=<?php echo $_GET['op']?>&tipo=<?php echo $_GET['tipo']?>&ciudad=<?php echo $_GET['ciudad']?>&zona=<?php echo $_GET['zona']?>&preciodesde=<?php echo $_GET['preciodesde']?>&preciohasta=<?php echo $_GET['preciohasta']?>&habitacionesdesde=<?php echo $_GET['habitacionesdesde']?>&habitacioneshasta=<?php echo $_GET['habitacioneshasta']?>&domicilio=<?php echo $_GET['domicilio']?>&ref=<?php echo $_GET['ref']?>&pileta=<?php echo $_GET['pileta']?>&llaves=<?php echo $_GET['llaves']?>&ocupada=<?php echo $_GET['ocupada']?>&plantabaja=<?php echo $_GET['plantabaja']?>&estado=<?php echo $_GET['estado']?>"><li><?php echo $i+1?></li></a>
				        <?php endfor ?>
                        <a class="<?php if ($_GET['pagina']>=$paginas){echo 'is-disabled';}?>" href="propiedades.php?pagina=<?php echo $_GET["pagina"]+1?>&op=<?php echo $_GET['op']?>&tipo=<?php echo $_GET['tipo']?>&ciudad=<?php echo $_GET['ciudad']?>&zona=<?php echo $_GET['zona']?>&preciodesde=<?php echo $_GET['preciodesde']?>&preciohasta=<?php echo $_GET['preciohasta']?>&habitacionesdesde=<?php echo $_GET['habitacionesdesde']?>&habitacioneshasta=<?php echo $_GET['habitacioneshasta']?>&domicilio=<?php echo $_GET['domicilio']?>&ref=<?php echo $_GET['ref']?>&pileta=<?php echo $_GET['pileta']?>&llaves=<?php echo $_GET['llaves']?>&ocupada=<?php echo $_GET['ocupada']?>&plantabaja=<?php echo $_GET['plantabaja']?>&estado=<?php echo $_GET['estado']?>"><li>></li></a>
                    </ul>
                </div>
            </div>  
        </main>
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <!--/* End Main */-->
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    </div>
    <script src="index.js"></script>
</body>
</html>