<?php
include 'connect.php';
if(!isset($_POST['operacion'])){$_POST['operacion']= ' ';};
if(!isset($_POST['tipo'])){$_POST['tipo']= ' ';};
if(!isset($_POST['codigopostal'])){$_POST['codigopostal']= ' ';};
if(!isset($_POST['tipocalle'])){$_POST['tipocalle']= ' ';};
if(!isset($_POST['calle'])){$_POST['calle']= ' ';};
if(!isset($_POST['altura'])){$_POST['altura']= ' ';};
if(!isset($_POST['ciudad'])){$_POST['ciudad']= ' ';};
if(!isset($_POST['zona'])){$_POST['zona']= ' ';};
if(!isset($_POST['piso'])){$_POST['piso']= ' ';};
if(!isset($_POST['puerta'])){$_POST['puerta']= ' ';};
if(!isset($_POST['bloque'])){$_POST['bloque']= ' ';};
if(!isset($_POST['ocupada'])){$_POST['ocupada']= ' ';};
if(!isset($_POST['coordenadas'])){$_POST['coordenadas']= ' ';};
if(!isset($_POST['toilettes'])){$_POST['toilettes']= ' ';};
if(!isset($_POST['plantas'])){$_POST['plantas']= ' ';};
if($_POST['metrosutiles'] == ''){$_POST['metrosutiles']= '1';};
if(!isset($_POST['supconstruida'])){$_POST['supconstruida']= ' ';};
if(!isset($_POST['banios'])){$_POST['banios']= ' ';};
if(!isset($_POST['anioconstruccion'])){$_POST['anioconstruccion']= ' ';};
if(!isset($_POST['mtscocina'])){$_POST['mtscocina']= ' ';};
if(!isset($_POST['habitaciones'])){$_POST['habitaciones']= ' ';};
if(!isset($_POST['expensas'])){$_POST['expensas']= ' ';};
if(!isset($_POST['ambientes'])){$_POST['ambientes']= ' ';};
if(!isset($_POST['comedor'])){$_POST['comedor']= ' ';};
if(!isset($_POST['living'])){$_POST['living']= ' ';};
if(!isset($_POST['lote'])){$_POST['lote']= ' ';};
if(!isset($_POST['plantabaja'])){$_POST['plantabaja']= ' ';};
if(!isset($_POST['estadogeneral'])){$_POST['estadogeneral']= ' ';};
if(!isset($_POST['carpinteriaext'])){$_POST['carpinteriaext']= ' ';};
if(!isset($_POST['suelo'])){$_POST['suelo']= ' ';};
if(!isset($_POST['orientacion'])){$_POST['orientacion']= ' ';};
if(!isset($_POST['aguacaliente'])){$_POST['aguacaliente']= ' ';};
if(!isset($_POST['carpinteriaint'])){$_POST['carpinteriaint']= ' ';};
if(!isset($_POST['calefaccion'])){$_POST['calefaccion']= ' ';};
if(!isset($_POST['tipococina'])){$_POST['tipococina']= ' ';};
if(!isset($_POST['alarma'])){$_POST['alarma']= ' ';};
if(!isset($_POST['agua'])){$_POST['agua']= ' ';};
if(!isset($_POST['aireacondicionadocentral'])){$_POST['aireacondicionadocentral']= ' ';};
if(!isset($_POST['aireacondicionado'])){$_POST['aireacondicionado']= ' ';};
if(!isset($_POST['bar'])){$_POST['bar']= ' ';};
if(!isset($_POST['alarmaincendio'])){$_POST['alarmaincendio']= ' ';};
if(!isset($_POST['alarmarobo'])){$_POST['alarmarobo']= ' ';};
if(!isset($_POST['altillo'])){$_POST['altillo']= ' ';};
if(!isset($_POST['cajafuerte'])){$_POST['cajafuerte']= ' ';};
if(!isset($_POST['parrilla'])){$_POST['parrilla']= ' ';};
if(!isset($_POST['asensor'])){$_POST['asensor']= ' ';};
if(!isset($_POST['balcon'])){$_POST['balcon']= ' ';};
if(!isset($_POST['chimenea'])){$_POST['chimenea']= ' ';};
if(!isset($_POST['electrodomesticos'])){$_POST['electrodomesticos']= ' ';};
if(!isset($_POST['calefaccionfriocalor'])){$_POST['calefaccionfriocalor']= ' ';};
if(!isset($_POST['centrico'])){$_POST['centrico']= ' ';};
if(!isset($_POST['garaje'])){$_POST['garaje']= ' ';};
if(!isset($_POST['garajedoble'])){$_POST['garajedoble']= ' ';};
if(!isset($_POST['gasnatural'])){$_POST['gasnatural']= ' ';};
if(!isset($_POST['galeria'])){$_POST['galeria']= ' ';};
if(!isset($_POST['habjuegos'])){$_POST['habjuegos']= ' ';};
if(!isset($_POST['hidromasaje'])){$_POST['hidromasaje']= ' ';};
if(!isset($_POST['lineatelefonica'])){$_POST['lineatelefonica']= ' ';};
if(!isset($_POST['gimnasio'])){$_POST['gimnasio']= ' ';};
if(!isset($_POST['jardin'])){$_POST['jardin']= ' ';};
if(!isset($_POST['lavadero'])){$_POST['lavadero']= ' ';};
if(!isset($_POST['patio'])){$_POST['patio']= ' ';};
if(!isset($_POST['jacuzzi'])){$_POST['jacuzzi']= ' ';};
if(!isset($_POST['luz'])){$_POST['luz']= ' ';};
if(!isset($_POST['sauna'])){$_POST['sauna']= ' ';};
if(!isset($_POST['preinstaacc'])){$_POST['preinstaacc']= ' ';};
if(!isset($_POST['luminoso'])){$_POST['luminoso']= ' ';};
if(!isset($_POST['piletapropia'])){$_POST['piletapropia']= ' ';};
if(!isset($_POST['piletacompartida'])){$_POST['piletacompartida']= ' ';};
if(!isset($_POST['riegoautomatico'])){$_POST['riegoautomatico']= ' ';};
if(!isset($_POST['amueblado'])){$_POST['amueblado']= ' ';};
if(!isset($_POST['puertablindada'])){$_POST['puertablindada']= ' ';};
if(!isset($_POST['portonautomatico'])){$_POST['portonautomatico']= ' ';};
if(!isset($_POST['solarium'])){$_POST['solarium']= ' ';};
if(!isset($_POST['pergola'])){$_POST['pergola']= ' ';};
if(!isset($_POST['tv'])){$_POST['tv']= ' ';};
if(!isset($_POST['videoportero'])){$_POST['videoportero']= ' ';};
if(!isset($_POST['satelite'])){$_POST['satelite']= ' ';};
if(!isset($_POST['vestuario'])){$_POST['vestuario']= ' ';};
if(!isset($_POST['buardilla'])){$_POST['buardilla']= ' ';};
if(!isset($_POST['habitacionservicio'])){$_POST['habitacionservicio']= ' ';};
if(!isset($_POST['arboles'])){$_POST['arboles']= ' ';};
if(!isset($_POST['autobuses'])){$_POST['autobuses']= ' ';};
if(!isset($_POST['centrocomercial'])){$_POST['centrocomercial']= ' ';};
if(!isset($_POST['colegios'])){$_POST['colegios']= ' ';};
if(!isset($_POST['costa'])){$_POST['costa']= ' ';};
if(!isset($_POST['golf'])){$_POST['golf']= ' ';};
if(!isset($_POST['hospitales'])){$_POST['hospitales']= ' ';};
if(!isset($_POST['subte'])){$_POST['subte']= ' ';};
if(!isset($_POST['montania'])){$_POST['montania']= ' ';};
if(!isset($_POST['urbanizacion'])){$_POST['urbanizacion']= ' ';};
if(!isset($_POST['rural'])){$_POST['rural']= ' ';};
if(!isset($_POST['vistamar'])){$_POST['vistamar']= ' ';};
if(!isset($_POST['tren'])){$_POST['tren']= ' ';};
if(!isset($_POST['zonasinfantiles'])){$_POST['zonasinfantiles']= ' ';};
if(!isset($_POST['residencial'])){$_POST['residencial']= ' ';};
if(!isset($_POST['barriocerrado'])){$_POST['barriocerrado']= ' ';};
if(!isset($_POST['descripcioncorta'])){$_POST['descripcioncorta']= ' ';};
if(!isset($_POST['descripcionlarga'])){$_POST['descripcionlarga']= ' ';};
if(!isset($_POST['fotoportada'])){$_POST['fotoportada']= ' ';};
if(!isset($_POST['galeriafotos'])){$_POST['galeriafotos']= ' ';};
if(!isset($_POST['descripcionmediana'])){$_POST['descripcionmediana']= ' ';};
if(!isset($_POST['captadopor'])){$_POST['captadopor']= ' ';};
if(!isset($_POST['contactadopor'])){$_POST['contactadopor']= ' ';};
if(!isset($_POST['oficina'])){$_POST['oficina']= ' ';};
if(!isset($_POST['llavero'])){$_POST['llavero']= ' ';};
if($_POST['preciopropietario'] == ''){$_POST['preciopropietario']= 0;};
if($_POST['porcentajesobrecompra'] == ''){$_POST['porcentajesobrecompra']= 0;};
if($_POST['comisionfija'] == ''){$_POST['comisionfija']= 0;};
if($_POST['precioanterior'] == ''){$_POST['precioanterior']= 0;};
if($_POST['tasacion'] == ''){$_POST['tasacion']= 0;};
if($_POST['parcela'] == ''){$_POST['parcela']= 0;};
if($_POST['lote'] == ''){$_POST['lote']= 0;};
if($_POST['tomo'] == ''){$_POST['tomo']= 0;};
if($_POST['libro'] == ''){$_POST['libro']= 0;};
if($_POST['folio'] == ''){$_POST['folio']= 0;};
if($_POST['registro'] == ''){$_POST['registro']= 0;};
if($_POST['ref_catastral'] == ''){$_POST['ref_catastral']= 0;};
if($_POST['valor_catastral'] == ''){$_POST['valor_catastral']= 0;};
if($_POST['contacto_id'] == ''){$_POST['contacto_id']= 0;};

do{
    $caracteres_permitidos1 = 'ABFGHIJKLMNOPQRSUVYZ';
    $caracteres_permitidos2 = '0123456789';
    $longitudLetra = 1;
    $longitudNumero = 4;
    $refLetra = substr(str_shuffle($caracteres_permitidos1), 0, $longitudLetra);
    $refNumero = substr(str_shuffle($caracteres_permitidos2), 0, $longitudNumero);
    $ref = $refLetra.$refNumero;
    $verRef = $connect-> prepare ("SELECT `referencia_interna` FROM `wp_propiedades` WHERE referencia_interna = ?");
    $verRef->execute ([$ref]);
    $refExiste = $verRef->fetchColumn();
}while ($refExiste > 0);



$operacion = $_POST['operacion'];
$tipo = $_POST['tipo'];
$codigoPostal = $_POST['codigopostal'];
$tipoCalle = $_POST['tipocalle'];
$calle = $_POST['calle'];
$altura = $_POST['altura'];
$ciudad = $_POST['ciudad'];
$zona = $_POST['zona'];
$piso = $_POST['piso'];
$puerta = $_POST['puerta'];
$bloque = $_POST['bloque'];
$ocupada = $_POST['ocupada'];
$coordenadas = $_POST['coordenadas'];
$toilettes = $_POST['toilettes'];
$plantas = $_POST['plantas'];
$metrosUtiles = $_POST['metrosutiles'];
$supConstruida = $_POST['supconstruida'];
$rebaniosf = $_POST['banios'];
$anioConstruccion = $_POST['anioconstruccion'];
$mtsCocina = $_POST['mtscocina'];
$habitaciones = $_POST['habitaciones'];
$expensas = $_POST['expensas'];
$ambientes = $_POST['ambientes'];
$comedor = $_POST['comedor'];
$living = $_POST['living'];
$lote = $_POST['lote'];
$plantaBaja = $_POST['plantabaja'];
$estadoGeneral = $_POST['estadogeneral'];
$carpinteriaExt = $_POST['carpinteriaext'];
$suelo = $_POST['suelo'];
$orientacion = $_POST['orientacion'];
$aguacaliente = $_POST['aguacaliente'];
$carpinteriaint = $_POST['carpinteriaint'];
$calefaccion = $_POST['calefaccion'];
$tipoCocina = $_POST['tipococina'];
$alarma = $_POST['alarma'];
$agua = $_POST['agua'];
$aireAcondicionadoCentral = $_POST['aireacondicionadocentral'];
$aireAcondicionado = $_POST['aireacondicionado'];
$bar = $_POST['bar'];
$alarmaIncendio = $_POST['alarmaincendio'];
$alarmaRobo = $_POST['alarmarobo'];
$altillo = $_POST['altillo'];
$cajaFuerte = $_POST['cajafuerte'];
$parrilla = $_POST['parrilla'];
$asensor = $_POST['asensor'];
$balcon = $_POST['balcon'];
$chimenea = $_POST['chimenea'];
$electroDomesticos = $_POST['electrodomesticos'];
$calefaccionFrioCalor = $_POST['calefaccionfriocalor'];
$centrico = $_POST['centrico'];
$garaje = $_POST['garaje'];
$garajeDoble = $_POST['garajedoble'];
$gasNatural = $_POST['gasnatural'];
$galeria = $_POST['galeria'];
$habJuegos = $_POST['habjuegos'];
$hidroMasaje = $_POST['hidromasaje'];
$lineaTelefonica = $_POST['lineatelefonica'];
$gimnasio = $_POST['gimnasio'];
$jardin = $_POST['jardin'];
$lavadero = $_POST['lavadero'];
$patio = $_POST['patio'];
$jacuzzi = $_POST['jacuzzi'];
$luz = $_POST['luz'];
$sauna = $_POST['sauna'];
$preinstaacc = $_POST['preinstaacc'];
$luminoso = $_POST['luminoso'];
$piletapropia = $_POST['piletapropia'];
$piletacompartida = $_POST['piletacompartida'];
$riegoautomatico = $_POST['riegoautomatico'];
$amueblado = $_POST['amueblado'];
$puertaBlindada = $_POST['puertablindada'];
$portonAutomatico = $_POST['portonautomatico'];
$solarium = $_POST['solarium'];
$pergola = $_POST['pergola'];
$tv = $_POST['tv'];
$videoPortero = $_POST['videoportero'];
$satelite = $_POST['satelite'];
$vestuario = $_POST['vestuario'];
$buardilla = $_POST['buardilla'];
$habitacionServicio = $_POST['habitacionservicio'];
$arboles = $_POST['arboles'];
$autobuses = $_POST['autobuses'];
$centroComercial = $_POST['centrocomercial'];
$colegios = $_POST['colegios'];
$costa = $_POST['costa'];
$golf = $_POST['golf'];
$hospitales = $_POST['hospitales'];
$subte = $_POST['subte'];
$montania = $_POST['montania'];
$urbanizacion = $_POST['urbanizacion'];
$rural = $_POST['rural'];
$vistaMar = $_POST['vistamar'];
$tren = $_POST['tren'];
$zonasInfantiles = $_POST['zonasinfantiles'];
$residencial = $_POST['residencial'];
$barrioCerrado = $_POST['barriocerrado'];
$descripcionCorta = $_POST['descripcioncorta'];
$descripcionLarga = $_POST['descripcionlarga'];
$fotoPortada = $_POST['fotoportada'];
$galeriaFotos = $_POST['galeriafotos'];
$descripcionMediana = $_POST['descripcionmediana'];
$captadoPor = $_POST['captadopor'];
$contactadoPor = $_POST['contactadopor'];
$oficina = $_POST['oficina'];
$llavero = $_POST['llavero'];
$precioproPietario = $_POST['preciopropietario'];
$porcentajeSobreCompra = $_POST['porcentajesobrecompra'];
$comisionFija = $_POST['comisionfija'];
$precioAnterior = $_POST['precioanterior'];
$tasacion = $_POST['tasacion'];
$parcela = $_POST['tasacion'];
$lote = $_POST['lote'];
$tomo = $_POST['tomo'];
$libro = $_POST['libro'];
$folio = $_POST['folio'];
$registro = $_POST['registro'];
$refCatastral = $_POST['ref_catastral'];
$valorCatastral = $_POST['valor_catastral'];
$contactoId = $_POST['contacto_id'];

$registrar = $connect-> prepare ("INSERT INTO wp_propiedades (referencia_interna, operacion_id, tipo_propiedad_id, cod_postal, tipo_calle_id, calle, altura, ciudad_id, zona_id, piso, puerta, bloque, ocupada, coordenadas, nro_toilettes, nro_plantas, metros_utiles, supeficie_construida, nro_banios, anio_contruccion, mts_cocina, cant_habitaciones, expensas, cant_ambientes, mts_comendor, mts_living, mts_lote, planta_baja, estado_general_id, estado_carpinteria_externa_id, tipo_suelo_id, orientacion, agua_caliente_id, estado_carpinteria_interna_id, tipo_calefaccion_id, tipo_cocina_id, alarma, agua, aire_acondicionado_central, aire_acondicionado, bar, alarma_incendio, alarma_robo, altillo, caja_fuerte, parrilla, asensor, balcon, chimenea, electrodomesticos, calefaccion_frio_calor, centrico, garaje, garaje_doble, gas_natural, galeria, hab_juegos, hidromasaje, linea_telefonica, gimnacio, jardin, lavadero, patio, jacuzzi, luz, sauna, preinst_aacc, luminoso, pileta_propia, pileta_compartida, riego_automatico, amueblado, puerta_blindada, porton_automatico, solarium, pergola, tv, videoportero, satelite, vestuario, buardilla, habitacion_servicio, arboles, autobuses, centro_comercial, colegios, costa, golf, hospitales, subte, montania, urbanizacion, rural, vista_al_mar, tren, zonas_infantiles, residencial, barrio_cerrado, descripcion_corta, descripcion_completa, foto_portada, galeria_fotos, descripcion_mediana, captado_por, contactado_por, oficina_id, llavero, precio_propietario, porcentaje_comision, comision_fija, precio_anterior, tasacion, parcela, lote, tomo, libro, folio, registro, ref_catastral, valor_catastral, propietarios) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? , ?, ?, ?, ?, ?, ?, ?, ?)");
$registrar->execute([$ref, $operacion, $tipo, $codigoPostal, $tipoCalle, $calle, $altura, $ciudad, $zona, $piso, $puerta, $bloque, $ocupada, $coordenadas, $toilettes, $plantas, $metrosUtiles, $supConstruida, $rebaniosf, $anioConstruccion, $mtsCocina, $habitaciones, $expensas, $ambientes, $comedor, $living, $lote, $plantaBaja, $estadoGeneral, $carpinteriaExt, $suelo, $orientacion, $aguacaliente, $carpinteriaint, $calefaccion, $tipoCocina, $alarma, $agua, $aireAcondicionadoCentral, $aireAcondicionado, $bar, $alarmaIncendio, $alarmaRobo, $altillo, $cajaFuerte, $parrilla, $asensor, $balcon, $chimenea, $electroDomesticos, $calefaccionFrioCalor, $centrico, $garaje, $garajeDoble, $gasNatural, $galeria, $habJuegos, $hidroMasaje, $lineaTelefonica, $gimnasio, $jardin, $lavadero, $patio, $jacuzzi, $luz, $sauna, $preinstaacc, $luminoso, $piletapropia, $piletacompartida, $riegoautomatico, $amueblado, $puertaBlindada, $portonAutomatico, $solarium, $pergola, $tv, $videoPortero, $satelite, $vestuario, $buardilla, $habitacionServicio, $arboles, $autobuses, $centroComercial, $colegios, $costa, $golf, $hospitales, $subte, $montania, $urbanizacion, $rural, $vistaMar, $tren, $zonasInfantiles, $residencial, $barrioCerrado, $descripcionCorta, $descripcionLarga, $fotoPortada, $galeriaFotos, $descripcionMediana, $captadoPor, $contactadoPor, $oficina, $llavero, $precioproPietario, $porcentajeSobreCompra, $comisionFija, $precioAnterior, $tasacion, $parcela, $lote, $tomo, $libro, $folio, $registro, $refCatastral, $valorCatastral, $contactoId]);